"""Update ChatHistory

Revision ID: 418f30fbc5b8
Revises: 977ab451955d
Create Date: 2024-12-27 15:44:25.950685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418f30fbc5b8'
down_revision: Union[str, None] = '977ab451955d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('chat_history', 'messages', server_default="")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
